// AUTO-GENERATED by scripts/generate-country-shapes.mjs — do not edit by hand.
// Detailed Sri Lanka coastline + delivery cities, projected into the
// WhyChooseUs map panel's viewBox="0 0 200 240".

export type SriLankaCity = { name: string; cx: number; cy: number; delay: number };

export const SRI_LANKA_PATH = "M65.9,38.8L63.4,39.3L61.3,36.5L60.8,35.2L61.3,34.4L61.9,34L62.6,34.1L63.5,36.8ZM62,63.2L63.2,66.3L59.8,64.2L57.5,62.4L56.6,60.9L61.4,62.5ZM66.5,31.2L70.4,31.4L74.7,31.2L77.7,31.8L82.8,38.3L96.6,49.9L104.3,61.7L104.9,64.3L105.9,66.5L107.7,67.1L109.3,68.1L116.8,79.5L117.7,81.8L117.5,84.2L118,86L120.1,87L122.5,87.4L124.1,89.2L126.2,98.2L126.2,101L126.6,102.3L136.2,116.3L136.8,118L136.6,119.3L136.9,120.4L138.7,122.9L141.7,129.6L143.1,131.1L144.9,137L145,148.2L144.4,153.2L142.6,159.2L140.5,165.1L138.1,169.4L135,173L124.4,180.7L121.3,182.3L107.4,187.1L97.2,191.6L87.7,192.8L78.3,190.4L71.1,184.4L67.5,175.5L65,166.3L61.3,156.1L58.6,124.6L57.2,115.7L55,104.4L55.3,99.6L56.8,94.9L56.8,105.2L58.1,106.4L59.2,105.1L60.2,94.5L61,90L64.7,78.3L64.9,76.1L64.1,71.7L64.3,69.5L69.9,61.3L71.3,56.5L72,51.6L71.7,46.3L70.7,41L75.3,42.7L77.8,44.5L80.4,45.8L82.5,45.1L84.9,45.1L83.2,42.2L77.8,39.6L69,38L66.3,35.9L65.3,34.1L65.7,32Z";

export const SRI_LANKA_CITIES: SriLankaCity[] = [
  { name: "Colombo", cx: 61.4, cy: 152, delay: 0 },
  { name: "Kandy", cx: 93.7, cy: 136.9, delay: 0.25 },
  { name: "Galle", cx: 76.3, cy: 188.7, delay: 0.4 },
  { name: "Jaffna", cx: 67.6, cy: 37.6, delay: 0.55 },
  { name: "Batticaloa", cx: 137.6, cy: 118.9, delay: 0.7 },
  { name: "Kalutara", cx: 65.5, cy: 166.6, delay: 0.15 },
  { name: "Matara", cx: 89.6, cy: 192.8, delay: 0.5 },
];
